import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/pages/Home/Home.module.css'
import Header from '@/components/Header'
import TextTransition, { presets } from "react-text-transition";
import { useState, useEffect } from 'react'

const Home = () => {

  const TEXTS = [
    (<div>미래를 주도할 🚀<br />역량있는 상당인,</div>),
    (<div>상상하라,<br/>당당하라!</div>)
  ]
  const [index, setIndex] = useState(0);
    useEffect(() => {
        const intervalId = setInterval(() =>
            setIndex(index => index + 1),
            5000
        );
        return () => clearTimeout(intervalId);
    }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.video_box}>
        <div className={styles.video_text_box}>
          <div className={styles.video_top_text}>
            상당고 학생인트라넷 🏫
          </div>
          <div className={styles.video_text}>
            <TextTransition springConfig={presets.default}>
              {TEXTS[index % TEXTS.length]}
            </TextTransition>
            <br/>오직 <span className={styles.highlight}>상당고에서.</span>
          </div>
          <Image
            src="/images/down_arrow.svg"
            className={styles.down_arrow}
            width={20}
            height={20}
          // priority
          />
        </div>
        <video
          autoPlay={true}
          loop={true}
          width={'100%'}
          height={'100%'}
          muted={true}
          className={styles.video}
        >
          <source src="https://sangdango.r2.ptj.kr/intro_video.mp4" type='video/mp4' />
        </video>
      </div>
    </>
  )
}

export default Home