import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/pages/Home/Home.module.css'
import Header from '@/components/Header'
import TextTransition, { presets } from "react-text-transition"
import { useState, useEffect, useRef } from 'react'
import classNames from 'classnames'
import toast from 'react-hot-toast'
import { useRouter } from 'next/router'

const Home = () => {

  const TEXTS = [
    (<div>미래를 주도할 🚀<br />역량있는 상당인,</div>),
    (<div>상상하라,<br />당당하라!</div>)
  ]
  const [index, setIndex] = useState(0);
  const [videoClass, setVideoClass] = useState(styles.video)
  const videoRef = useRef()
  const router = useRouter()
  useEffect(() => {
    toast('아직 서비스가 준비중입니다.',
      {
        icon: '⏳',
      }
    );
    const intervalId = setInterval(() =>
      setIndex(index => index + 1),
      5000
    )
    if (typeof window != undefined) {
      const handleResize = () => {
        let width = window.innerWidth
        let height = window.innerHeight
        if (width >= height * 2) {
          setVideoClass(classNames(styles.video, styles.video_bug))
        } else {
          setVideoClass(styles.video)
        }
      }
      window.addEventListener('resize', handleResize)
      return () => {
        window.removeEventListener('resize', handleResize)
        clearTimeout(intervalId)
      }
    }
    return () => clearTimeout(intervalId)
  }, [])

  return (
    <>
      <Head>
        <title>여기는 상당입니다</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.video_box}>
        <div className={styles.video_text_box}>
          <div className={styles.video_top_text}>
            상당고 학생인트라넷 🏫
          </div>
          <div className={styles.video_text}>
            <TextTransition springConfig={presets.default}>
              {TEXTS[index % TEXTS.length]}
            </TextTransition>
            <br />오직 <span className={styles.highlight}>상당고에서.</span>
          </div>
          <Image
            src="/images/down_arrow.svg"
            className={styles.down_arrow}
            width={20}
            height={20}
          />
        </div>
        <video
          ref={videoRef}
          autoPlay={true}
          loop={true}
          width={'100%'}
          height={'100%'}
          muted={true}
          className={videoClass}
        >
          <source src="https://cdn.sangdang.kr/intro_video.mp4" type='video/mp4' />
        </video>
      </div>
      <div className={styles.intro_big_text}>
        너만의 상당을 만들어봐
      </div>
      <div className={styles.intro_small_text}>
        아래 버튼을 눌러 이동하세요
      </div>
      <div className={styles.warp_container}>
        <div className={styles.warp_box} id={styles.club}>
          <div className={styles.warp_text_box}>
            <div className={styles.warp_big_text}>
              동아리 🔬
              <div className={styles.warp_big_small_text}>
                동아리를 손쉽게 관리.
              </div>
            </div>
            <div className={styles.warp_small_text}>눌러서 이동하기 →</div>
          </div>
        </div>
        <div className={styles.warp_box} id={styles.community} onClick={()=>toast('아직 준비중인 기능이에요!')}>
          <div className={styles.warp_text_box}>
            <div className={styles.warp_big_text}>
              커뮤니티 ✍️
              <div className={styles.warp_big_small_text}>
                사람이 여행하는 곳은 사람의 마음뿐이다
              </div>
            </div>
            <div className={styles.warp_small_text}>눌러서 이동하기 →</div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Home